halcyon/asdf-java

bin/install

For `adoptopenjdk` installs the `$variant` is set to `mac_hotspot`.
The `unpack_java` function uses the `$variant` value to determine how to install and had a case statement with no way of handling `mac_hotspot`. So `adoptopenjdk` will automatically fail.
This PR should fix that.

add mac_hotspot case to statement in unpack_java function

---

bin/functions
bin/list-legacy-filenames

So far I've been using jenv along with `.java-version` files, this would allow for migrating to asdf.

Add legacy filename support for jenv

---

.github/workflows/tests.yml
.travis.yml

Explicitly use the current git commit for running `asdf plugin-test`.
Otherwise, asdf will try to use the "master" branch for running its tests:
https://github.com/asdf-vm/asdf/blob/v0.7.6/lib/commands/command-plugin-test#L9

Fix the GitHub tests workflow

---

corretto/amazon-corretto-11.0.4.11.1-linux-x64.tar.gz.sha256.txt
corretto/amazon-corretto-11.0.4.11.1-macosx-x64.tar.gz.sha256.txt
corretto/amazon-corretto-11.0.5.10.1-linux-x64.tar.gz.sha256.txt
corretto/amazon-corretto-11.0.5.10.1-macosx-x64.tar.gz.sha256.txt
corretto/amazon-corretto-11.0.5.10.2-macosx-x64.tar.gz.sha256.txt
corretto/amazon-corretto-8.232.09.2-macosx-x64.tar.gz.sha256.txt
corretto/corretto.json

* Add Corretto 8.232.09.2 (macOS only)
* Add Corretto 11.0.4.11.1
* Add Corretto 11.0.5.10.1
* Add Corretto 11.0.5.10.2 (macOS only)

Update Amazon Corretto JDKs

---

zulu/zulu.json
zulu/zulu11.37.17-ca-jdk11.0.6-linux_x64.tar.gz.sha256.txt
zulu/zulu11.37.17-ca-jdk11.0.6-macosx_x64.tar.gz.sha256.txt
zulu/zulu13.29.9-ca-jdk13.0.2-linux_x64.tar.gz.sha256.txt
zulu/zulu13.29.9-ca-jdk13.0.2-macosx_x64.tar.gz.sha256.txt
zulu/zulu7.36.0.5-ca-jdk7.0.252-linux_x64.tar.gz.sha256.txt
zulu/zulu7.36.0.5-ca-jdk7.0.252-macosx_x64.tar.gz.sha256.txt
zulu/zulu8.44.0.9-ca-jdk8.0.242-linux_x64.tar.gz.sha256.txt
zulu/zulu8.44.0.9-ca-jdk8.0.242-macosx_x64.tar.gz.sha256.txt

Add latest versions of the Zulu OpenJDK 7, 8, 11, and 13 from Azul.

Add Zulu 7.36.0.5, 8.44.0.9, 11.37.17, 13.29.9

---

corretto/amazon-corretto-11.0.6.10.1-2-macosx-x64.tar.gz.sha256.txt
corretto/amazon-corretto-8.242.08.1-1-macosx-x64.tar.gz.sha256.txt
corretto/amazon-corretto-8.242.08.1-linux-x64.tar.gz.sha256.txt
corretto/corretto.json

Changelogs:
* https://github.com/corretto/corretto-8/blob/1a1a02e62547c5902a7af39772e48c0188e43b93/CHANGELOG.md#corretto-version-8242081
* https://github.com/corretto/corretto-11/blob/develop/CHANGELOG.md#corretto-version-1106101-2-macos
Releases:
* https://github.com/corretto/corretto-11/releases/tag/11.0.6.10.1-2
* https://github.com/corretto/corretto-8/releases/tag/8.242.08.1-1
* https://github.com/corretto/corretto-8/releases/tag/8.242.08.1

Add Corretto 8.242.08.1 and 11.0.6.10.1-2

---

.github/workflows/tests.yml
.travis.yml
bin/functions

This change set fixes all [ShellCheck](https://github.com/koalaman/shellcheck) warnings and errors in `bin/functions`.
<details>
Fixed warnings and errors:
```text
> shellcheck bin/functions
In bin/functions line 3:
PLUGIN_HOME=$(dirname $(dirname "${0}"))
^---------------^ SC2046: Quote this to prevent word splitting.
In bin/functions line 33:
trap "rm -rf ${TEMP_DIR}" EXIT
^---------^ SC2064: Use single quotes, otherwise this expands now rather than when signalled.
In bin/functions line 37:
bold=`tput bold`
^---------^ SC2006: Use $(...) notation instead of legacy backticked `...`.
Did you mean:
bold=$(tput bold)
In bin/functions line 38:
nc=`tput sgr0`
^---------^ SC2006: Use $(...) notation instead of legacy backticked `...`.
Did you mean:
nc=$(tput sgr0)
In bin/functions line 42: …
```

Fix ShellCheck warnings and make script more strict

---

bin/functions
corretto/corretto.json
zulu/zulu.json

The AdoptOpenJDK API v2 is deprecated and will eventually be shut down: https://api.adoptopenjdk.net/
Additionally, it currently has problems providing data for OpenJDK 13 in which `https://api.adoptopenjdk.net/v2/info/releases/openjdk13?type=jdk` returns an HTTP response with status 404 (Not Found).
Unfortunately the API response format changed slightly, so that the static data for Zulu Community and Amazon Corretto had to be updated, too.
https://api.adoptopenjdk.net/swagger-ui/
https://github.com/AdoptOpenJDK/openjdk-api-v3
Fixes #54

Migrate to AdoptOpenJDK API v3

---

bin/functions

Before deleting the temporary directory (`$TEMP_DIR`) at the end of the script,
make sure that it exists so that we don't accidentally delete the user's home directory.
Fixes #63

Check that temporary directory exists before deleting

---

bin/functions

Set exit trap only after `$TEMP_DIR` has been set and exit on unknown/invalid operating system or machine architecture.
Refs #63
Refs #64

Set exit trap only after TEMP_DIR has been set

---

corretto/corretto.json
zulu/zulu.json

Currently this plugin is not able to list releases from Corretto and Zulu. So they have to be updated manually.
https://github.com/corretto/corretto-8/releases/tag/8.252.09.1
https://github.com/corretto/corretto-11/releases/tag/11.0.7.10.1
https://www.azul.com/downloads/zulu-community/?architecture=x86-64-bit&package=jdk
https://www.azul.com/downloads/zulu-community/?architecture=x86-64-bit&package=jdk-fx

Amazon Corretto and Azul Zulu 11.0.7 / 8u252b14

---

set-java-home.fish

This changes `set-java-home.fish` so it will globally export JAVA_HOME. 
Related to issue #85

make set-java-home.fish export globally

---

README.md
bin/functions

Use BSD stat on macOS even if sha256sum is installed

---

bin/functions
set-java-home.bash
set-java-home.fish
set-java-home.zsh

This pull request is aimed to fix #109 
I only updated the code on the `functions` file, we should change in the `set-java-home.*` files too. I just need to get your feedback if I should:
1. Create another file in another folder with the function to be sourced by the other files;
2. Create the function in every file that needs it;
3. Source the `functions` file on the other files where the function is needed.
My personal preference would be for the first option, but I leave it here for discussion.

Replace realpath occurrences with a custom function

---

.travis.yml

The Java candidate `azul-zulu-8.44.0.11-jdk8.0.242` doesn't exist anymore.
Changed to `zulu-11.45.27` for the builds on Travis CI to succeed again.

Fix JDK version referenced in Travis CI build verification

---

.github/workflows/update-data.yaml

In some situations it might be useful to allow triggering the `update-date` workflow to update the release metadata manually.
https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

Allow manual dispatch of update-data workflow

---

set-java-home.fish

The `fish` shell has a builtin `realpath`, which should be used for this.
The `absolute_dir_path` function doesn't work as it might be expected to, and instead just traps the user inside the JAVA_HOME directory.
See https://github.com/fish-shell/fish-shell/issues/7780 and closes https://github.com/halcyon/asdf-java/issues/130.

Use fish builtin `realpath`

---

set-java-home.zsh

As created by @a4z and posted in https://github.com/halcyon/asdf-java/pull/136 this should fix #135 . Since I can't edit the original pull request I made a new one with the requested changes by @halcyon .

Use built-in zsh function to get absolute dir path take 2

---

.github/workflows/tests.yml
update_data.bash

In order to fix https://github.com/halcyon/asdf-java/issues/46 and https://github.com/halcyon/asdf-java/issues/57 I've added the jvm_impl after the vendor.
Unfortunately this will break the names configured previously in .tools-versions if you had selected one of the openj9 JDK's. Not sure how you can do this backwards compatible.

Add the JVM Implementation after the name of the Vendor

---

bin/exec-env

IMHO the plugin should set `JAVA_HOME` for all commands.
Bonus: 
Exporting `JAVA_HOME` in `exec-env` makes the plugin play nice with [asdf-direnv](https://github.com/asdf-community/asdf-direnv)

set JAVA_HOME in exec-env

---

.github/workflows/tests.yml

With https://github.com/halcyon/asdf-java/pull/140 I missed the fact that it would break the plugin-test step in the tests :(
adoptopenjdk-8.0.252+9.1.openj9-0.20.0 no longer exists, it's now adoptopenjdk-openj9-8.0.252+9.1.openj9-0.20.0
This pull request fixes that.

With the jvm_impl as part of the base name of the package the plugin-test broke

---

bin/functions

`asdf list all java` and other asdf plugin commands could run with rosetta emulation for X86_64 on apple silicon using the shell arch command so we need to make sure the cache file is invalidated when we target different architectures otherwise we would incorrectly use the cached file created from previous runs

Use platform specific cache files to store java release data

---

bin/functions

Resolves the following error that displays for users who do not set ASDF_DIR:
$HOME/.asdf/plugins/java/bin/list-all: line 3: /lib/utils.bash: No such file or directory
As indicated in the [official asdf docs][asdf docs], `ASDF_DIR` should default to `~/.asdf`, though asdf itself defaults to `$HOME/.asdf`:
> ASDF_DIR - Defaults to ~/.asdf - Location of the asdf scripts. If you install asdf to some other directory, set this to that directory. For example, if you are installing via the AUR, you should set this to /opt/asdf-vm.
[asdf docs]: http://asdf-vm.com/manage/configuration.html#environment-variables

Allow unset ASDF_DIR environment variable

---

bin/functions

Updates `retrieve-release-data()` to no longer silently fail, this was causing issues where I was having SSL issues, but could not diagnose them.
Current behavior:
``` console
$ asdf list-all java
No compatible versions available (java )
$ asdf install java liberica-1.8.0
grep: /tmp/asdf-java.cache/releases-linux-x86_64.tsv: No such file or directory
Unknown release: liberica-1.8.0
```
Proposed behaviour:
``` console
$ asdf install java liberica-1.8.0
curl: (60) SSL certificate problem: self-signed certificate in certificate chain
More details here: https://curl.se/docs/sslcerts.html
curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above. …
```

Removes silent fail from retrieve-release-data()

---

set-java-home.bash

asdf-java prepends to `$PROMPT_COMMAND`, thus swallowing up the previous command's exit code (normally the command the user invoked). This is troublesome if the exit code is used in the user's own prompt command, for example to output a different prompt.

Return with previous exit code in Bash prompt function

---

README.md

I also used code blocks because GitHub makes it easier to copy them with a built-in copy button.
Resolves halcyon/asdf-java#160

Add `latest:` syntax to the README

---

bin/functions

In a multi user environment it's possible that some other user has already created CACHE_DIR with its own permissions breaking this plugin. Add currently logged in user name into CACHE_DIR directory name so that it would be user specific and have correct permissions for every user

Create cache dir for currently logged in user

---

bin/functions

Fix #213.
To integrate jdk at user home, set `java_macos_integration_in_home = yes`.

Use user home to integrate java for macOS

---

bin/functions

We encountered an issue this morning where a [Github incident](https://www.githubstatus.com/incidents/fnq063tqh7cc) caused release artifact URLs to briefly return invalid content (the `tar.gz` file just had HTML instead). Even though the `tar` extraction failed, the overall `install` didn't and created bad cache entries in our CI system.

Fail install command if download extraction errors out
